source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'

xcodeproj 'TFashion.xcodeproj'
platform :ios, '7.1'

pod 'Reachability', '~> 3.2'
pod 'MBProgressHUD', '~> 0.9'
pod 'PonyDebugger', '~> 0.4.0'
pod 'Analytics'
pod 'TSMessages'
pod 'FontAwesomeKit'
pod 'SocialAccounts'
pod 'SimpleAuth/FacebookWeb'
pod 'SimpleAuth/TwitterWeb'
pod 'SimpleAuth/Instagram'
pod 'SimpleAuth/Tumblr'
pod 'TTTAttributedLabel'
pod 'DBCamera'
pod 'libPhoneNumber-iOS'
